### ISSUE TITLE
IndexError  on connectionHolder is some cases

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker7#23]
In some case the conncetionHolder can throw an IndexError

For example:
import spynnaker7.pyNN as p

p.setup(timestep=1)
pop_1 = p.Population(5, p.IF_curr_exp, {}, label="pop_1")
input = p.Population(5, p.SpikeSourceArray, {'spike_times': [0]},
                     label="input")
input_proj = p.Projection(input, pop_1,
                          p.OneToOneConnector(weights=5.0, delays=1),
                          target="excitatory")
#input_proj= p.Projection(input, pop_1, p.AllToAllConnector(
#    weights=5.0, delays=1))
repeat_proj = p.Projection(pop_1, pop_1,
                           p.OneToOneConnector(weights=5.0, delays=1),
                           target="excitatory")

p.run(20)
weights = input_proj.getWeights(format='array', gather=True)
#weights = input_proj.getWeights(format='list', gather=True)
print weights

Stack Trace:
Traceback (most recent call last):
  File "...mini.py", line 19, in <module>
    print weights
  File "sPyNNaker\spynnaker\pyNN\models\neuron\connection_holder.py", line 205, in __str__
    data = self._get_data_items()
  File "sPyNNaker\spynnaker\pyNN\models\neuron\connection_holder.py", line 177, in _get_data_items
    connections[item]
IndexError: index 72 is out of bounds for axis 1 with size 5

Note:
Does not happen if I remove the second projection
Does not happen on format="list"  (the default)

Not able to replicate in pynn8 so probably not a blocker.

**Comment by rowleya** [comment]
It looked like reading back the one-to-one direct matrix was generally broken - it must have only been working by luck in PyNN 0.8!

Fixed in SpiNNakerManchester/sPyNNaker#375

**Comment by alan-stokes** [comment]
fixed in master
