### ISSUE TITLE
Unable to initialize between runs if population on multiple cores

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker7#6]
ValueError: operands could not be broadcast together with shapes (27,) (100,)

See 
https://github.com/SpiNNakerManchester/sPyNNaker7/tree/master/p7_integration_tests/test_change_neuron_parameters_between_runs

test_run_split or main

**Comment by Christian-B** [comment]
Added farther tests.
Changing if_curr_exp does work.
--
changing SpikeSourcePoisson after a reset works too!

**Comment by pabogdan** [comment]
L30 in spike_source_poisson.py
```python
     # Convert end values as timesteps to durations in milliseconds
        self._duration[vertex_slice.as_slice] = \
            self._convert_n_timesteps_to_ms(
                values[1], self._machine_time_step) - self._start[vertex_slice.as_slice]

```

**Comment by Christian-B** [comment]
Added @rowleya fix in:
https://github.com/SpiNNakerManchester/sPyNNaker/pull/324

**Comment by Christian-B** [comment]
fix merged in.
